### ISSUE TITLE
[환불] 관리자는 환불 처리 목록의 상세 내역을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by subkka** [ssg-java3-240304/shop-Animal-Playground#14]
## 🌈 Success criteria

1. 상세 페이지는 주문 번호, 신청 일시, 처리 상태, 사유 타입, 사유 상세로 구성됩니다.
2. 사유 타입은 단순 변심, 상품 문제가 있습니다.
3. 관리자는 내용을 확인 후 처리 상태를 변경할 수 있습니다.
4. 환불된 상품들은 기존 상품과 따로 관리합니다.
5. 환불처리가 완료되면 자동으로 처리완료 상태로 변경됩니다.
6. 목록 버튼 클릭 시 환불 목록으로 돌아갑니다.

## 👷To-do

- [x] refund-mapper.xml에 환불 상세 데이터 조회 쿼리 작성
- [x] RefundMapperTest에서 환불 상세 조회 쿼리 테스트
- [x] findRefundDetailList() 메소드 생성
- [x] refundDetailList.html 생성
- [x] html에 환불 상세 데이터 삽입
- [x] 환불처리 완료 시 alert 뜨고 처리상태 처리완료로 변경
