### ISSUE TITLE
관리자는 재고가 부족한 상품들을 주문 취소 처리를 할 수 있습니다.

### ISSUE THREAD

**Issue by dhgudehd98** [ssg-java3-240304/shop-Animal-Playground#16]
## 🌈: Success criteria
1. 관리자는 주문 상태에 따라 주문에 대한 내역을 확인할 수 있습니다.
2. 주문 상태가 '입금전'인 상태에 한하여 주문한 상품들에 대한 재고들을 조회합니다.
3. 만약에 재고가 부족 할 경우 주문 내역에서 주문 상태를 'canceled'로 변경하고, 취소 목록에 주문한 주문을 넣습니다.
4. 취소 테이블에는 취소 번호 , 주문 번호 , 취소 처리 상태가 있습니다.
5. 취소 처리 상태에는 처리중, 처리 완료 상태가 있는데 관리자가 취소처리를 완료하면 상태값을 취소 완료로 변경합니다. 

## 👷: To-do
- [x] 주문 상태가 '입금전'인 상태에 한하여 주문한 상품들에 대한 재고를 조회 하는 테스트 코드 작성 
- [x] 주문 상태가 '입금전'인 상태에 한하여 주문한 상품들에 대한 재고를 조회 하는 로직 작성 
- [x] 재고가 부족한 주문들을 취소 목록에 추가하는 테스트 코드 작성
- [x] 재고가 부족한 주문들을 취소 목록에 추가하는 로직 작성 
- [x] 관리자가 취소처리를 완료하면 상태값을 취소 완료로 변경하는 테스트 코드 작성 
- [x] 관리자가 취소처리를 완료하면 상태값을 취소 완료로 변경하는 로직 작성

**Comment by dhgudehd98** [comment]
완료

**Comment by dhgudehd98** [comment]
완료
