### ISSUE TITLE
관리자는 총 매출 조회를 할 수 있고, 상품 카테고리별 판매현황과 고객의 동물종류 별로 판매현황을 조회합니다.

### ISSUE THREAD

**Issue by dhgudehd98** [ssg-java3-240304/shop-Animal-Playground#17]
# 🌈: Success criteria
1. 관리자는 배송완료된 주문 내역을 기준으로 총 매출을 조회 할 수 있습니다.
2. 동일한 상품 카테고리별로 판매현황을 파악하고, 시각적으로 쉽게 보기 위해서 pie-chart를 이용해서 출력합니다.
3. 고객의 품종 별로 판매현황을 파악하고, 시각적으로 쉽게 보기 위해서 pie-chart를 이용해서 출력합니다.
4. 관리자는 카테고리별 , 품종 별로 판매순위를 파악할 수 있습니다.
# 👷:To-do
- [x] 배송 완료 주문 내역 기준으로 총 매출 조회하는 테스트 코드 작성 
- [x] 배송 완료 주문 내역 기준으로 총 매출 조회하는 로직 작성 
- [x] 상품 카테고리별로 판매현황을 조회하는 테스트 코드 작성 
- [x] 상품 카테고리별로 판매현황을 파악하는 로직 작성 
- [x] 카테고리별, 품종 별로 판매 현황 파악하는 테스트 코드 작성
- [x] 카테고리별, 품종 별로 판매 현황 파악하는 로직 작성

**Comment by dhgudehd98** [comment]
완료
