### ISSUE TITLE
[상품]관리자는 상품을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by Parkminem** [ssg-java3-240304/shop-Animal-Playground#2]
# 🌈 Success criteria
1. 관리자는 상품을 등록할 수 있습니다.
2. 상품을 등록할 때는 상품이름, 카테고리, 상품이미지, 상품설명, 가격, 재고, 진열상태, 상품상태를 입력해야 합니다. 
# 👷To-do
- [x] 상품 등록 테스트 코드 작성
- [x] 상품 등록 메소드 작성
- [ ]  상품 등록 front 연결
