### ISSUE TITLE
[상품]관리자는 상품 목록을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by Parkminem** [ssg-java3-240304/shop-Animal-Playground#3]
# 🌈 Success criteria
1. 관리자는 등록된 상품 목록을 조회할 수 있습니다. 목록에서는 상품번호, 카테고리, 상품이름, 상품 이미지, 가격, 재고, 진열 상태, 상품 상태, 상품 등록일이 출력됩니다.
2. 관리자는 등록된 상품 목록을 “날짜별로보기” 버튼을 클릭하여 날짜별로 정렬하여 조회할 수 있습니다.
3. 관리자는 등록된 상품 목록을 “카테고리별로보기” 버튼을 클릭하여 카테고리별로 정렬하여 조회할 수 있습니다.
4. 관리자는 상품 목록에서 상세 보기 버튼을 클릭하여 특정 상품의 상세 조회 페이지로 이동할 수 있습니다.
5. 관리자는 등록된 상품을 삭제할 수 있습니다.

# 👷To-do
- [x] 상품 목록 조회 테스트 코드 작성
- [x] 상품 목록 조회 메소드 작성
- [x]  상품 목록 조회 front 연결
