### ISSUE TITLE
[상품]관리자는 특정 상품을 상세조회 할 수 있습니다.

### ISSUE THREAD

**Issue by Parkminem** [ssg-java3-240304/shop-Animal-Playground#4]
# 🌈 Success criteria
1. 관리자는 등록된 상품의 상세 정보를 조회할 수 있습니다. 상세 정보 조회에서는 상품번호, 카테고리, 상품이름, 상품이미지, 상품설명, 가격, 재고, 진열상태, 상품상태, 상품등록일이 출력됩니다.
2. 관리자는 등록된 상품의 상세 정보를 수정할 수 있습니다. 수정에서는 카테고리, 상품이름, 상품이미지, 상품설명, 가격, 재고, 진영상태, 상품상태를 수정할 수 있습니다.
3. 관리자는 상품 상세 조회 페이지에서 목록 버튼을 눌러, 상품 목록 페이지로 이동할 수 있습니다. 
4. 관리자는 등록된 상품을 삭제할 수 있습니다.

# 👷To-do
- [x] 상품 상세 조회 테스트 코드 작성
- [x] 상품 상세 조회 메소드 작성
- [x] 상품 상세 조회 front 연결
